### ISSUE TITLE
About your code 

### ISSUE THREAD

**Issue by sanwancoder** [ldwqh0/cache-test#1]
you can use **System.currentTimeMillis()** instead of   **new Date().getTime()**

and you can install plugins.

In addtion, it is not necessary for u to commit rebel.xml.  		

<dir name="D:/Users/LiDong/Projects/XYYH-GIT/cache-test/cache-simple/target/classes">

At last, thanks for your demo.  i learn something.

**Comment by ldwqh0** [comment]
@sanwancoder thanks
